<?php

namespace Costo\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AjusteVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AjusteVentaRepository extends EntityRepository
{
}